definitions:
  models.Response:
    properties:
      error:
        type: boolean
      segment:
        $ref: '#/definitions/models.Segment'
    type: object
  models.Segment:
    properties:
      id:
        type: integer
      payload:
        type: string
      segment_index:
        type: integer
      sender:
        type: string
      time:
        type: string
      total_length:
        type: integer
    type: object
info:
  contact:
    name: Дмитрий Белозеров ИУ5-64Б
    url: http://t.me/belozerovmsk
  description: Отправка текста. Передаваемую информацию защитить передаваемую информацию
    [7,4]-кодом Хэмминга. Длина сегмента (X) 150 байт, период сборки сегментов (N)
    2 секунд, вероятность ошибки (P) 8%, вероятность потери кадра (R) 1%.
  title: Вариант 11
paths:
  /code:
    post:
      consumes:
      - application/json
      description: Ручка защищает передаваемую информацию [7,4]-кодом Хэмминга.
      parameters:
      - description: Данные для передачи
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/models.Response'
        "409":
          description: Пакет утерян
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.Response'
      summary: код Хэмминга
      tags:
      - Channel
swagger: "2.0"
